// permissions.js
// Centralized permission scopes and role associations

const PERMISSIONS = {
  // Appointments
  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_WRITE: 'APPOINTMENT_WRITE',
  APPOINTMENT_MANAGE: 'APPOINTMENT_MANAGE', // managing doctors and hospitals

  // Audit logs
  AUDIT_READ: 'AUDIT_READ',
  AUDIT_MANAGE: 'AUDIT_MANAGE',

  // FinOps
  FINOPS_READ: 'FINOPS_READ',
  FINOPS_MANAGE: 'FINOPS_MANAGE',

  // Users management
  USER_READ: 'USER_READ',
  USER_WRITE: 'USER_WRITE',
  USER_MANAGE: 'USER_MANAGE',

  // Notification preferences and logs
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE'
};

// Roles: SUPER_ADMIN, ADMIN, CAREGIVER, USER
const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.FINOPS_READ,
    PERMISSIONS.FINOPS_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_MANAGE
  ],
  ADMIN: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_MANAGE
  ],
  CAREGIVER: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTIFICATION_READ
  ],
  USER: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTIFICATION_READ
  ]
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS
};
